### ISSUE TITLE
Please add this to pypi

### ISSUE THREAD

**Issue by cubimon** [kz6fittycent/BobRossQuotes#1]
I would like to get the quotes generated on macos

**Comment by kz6fittycent** [comment]
Let me think about this. I really only wanted to support this as a snap, and I've got quite a few projects that I'm currently managing. If you would like to contribute to this repo by forking it, and submitting PR's, to include managing the `pypi` deployments and updates, I very much welcome your help!

**Comment by kz6fittycent** [comment]
I am going to pass on adding this to `pypi`. I would love it if you'd like to contribute to the project and add/support the `pypi` version.

**Comment by cubimon** [comment]
Yes I would definitely like to do this when I find some time, I know it shouldn't be much, just some copy and paste

**Comment by kz6fittycent** [comment]
Awesome! Glad to you're willing to help. Just submit a PR for any code or steps you're taking so we can add it (e.g. installation directions for `pypi`, etc).

**Comment by cubimon** [comment]
I did the following:

Build:

`python setup.py sdist`

Upload to production PyPI:

`python upload dist/*`

Upload to test PyPI:

`twine upload -r testpypi dist/*`

My `~/.pypirc` looks like this:

```
[distutils]
index-servers =
    pypi
    testpypi

[pypi]
repository = https://upload.pypi.org/legacy/
username = __token__
password = ${replace this with the token}

[testpypi]
repository = https://test.pypi.org/legacy/.
username = __token__
password = ${replace this with the token}
```

You can find it now at https://pypi.org/project/bobross/1.1/. The README is quite broken, I guess we would need a separate README for PyPI. `bobross` executable script seems to be included as well :)

**Comment by kz6fittycent** [comment]
Does PyPi not respect `markdown`? That's how it's done in GH. That said, you could edit the README on PyPi to be even more basic, with just the commands and a link back to this repo.

**Comment by kz6fittycent** [comment]
I'm satisfied that we've accomplished what's needed for the addition. If you want to handle the `pypi` stuff, I'd appreciate it. I've already updated the README here to include the `pip` directions. I'll close this issue. 

Thanks again!
