### ISSUE TITLE
Snap store page: URL to developper website  is a dead link

### ISSUE THREAD

**Issue by Dadu042** [kz6fittycent/BobRossQuotes#2]
It links to: https://github.com/kz6fittycent/bobrossquotes-snap
instead of: https://github.com/kz6fittycent/BobRossQuotes

Funny app. Maybe a few more ASCII graphics would help to make it a hit ! ;)

**Comment by kz6fittycent** [comment]
I just pushed a fix. Should be deployed shortly. Feel free to for the repo and submit a PR with more ascii! I am happy to take a look at what you provide.
